version: '3.9'

services:
  jupyter:
    image: jupyter/scipy-notebook
    ports:
      - 8888
    volumes:
      - type: bind
        source: ./notebooks
        target: /home/jovyan/work
      - type: bind
        source: ./jupyter
        target: /home/jovyan/.jupyter
